_Z37UnityEngine_Transform__get_childCountPvS_ = 0x02ae3420 - 0x056E6000;
_Z54UnityEngine_Events_UnityAction_SettingMenuItem____ctorPvS_S_PKv = 0x0284fa10 - 0x056E6000;
_Z29Dpr_UI_SettingMenuItem__SetupPviiS_S_S_ = 0x0214ad70 - 0x056E6000;
_Z53System_Collections_Generic_List_SettingMenuItem___AddPvS_S_ = 0x02badd00 - 0x056E6000;
_Z17il2cpp_object_newPv = 0x000519e0 - 0x056E6000;
_Z27System_String__CreateStringPvS_S_ = 0x02948980 - 0x056E6000;
