#pragma once

#include "il2cpp.h"

intptr_t UnityEngine_Rendering_CommandBuffer__InitBuffer (const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__ReleaseBuffer (UnityEngine_Rendering_CommandBuffer_o* __this, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__set_name (UnityEngine_Rendering_CommandBuffer_o* __this, System_String_o* value, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Clear (UnityEngine_Rendering_CommandBuffer_o* __this, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Internal_DrawMesh (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Mesh_o* mesh, UnityEngine_Matrix4x4_o matrix, UnityEngine_Material_o* material, int32_t submeshIndex, int32_t shaderPass, UnityEngine_MaterialPropertyBlock_o* properties, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__CopyTexture_Internal (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o* src, int32_t srcElement, int32_t srcMip, int32_t srcX, int32_t srcY, int32_t srcWidth, int32_t srcHeight, UnityEngine_Rendering_RenderTargetIdentifier_o* dst, int32_t dstElement, int32_t dstMip, int32_t dstX, int32_t dstY, int32_t mode, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit_Texture (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Texture_o* source, UnityEngine_Rendering_RenderTargetIdentifier_o* dest, UnityEngine_Material_o* mat, int32_t pass, UnityEngine_Vector2_o scale, UnityEngine_Vector2_o offset, int32_t sourceDepthSlice, int32_t destDepthSlice, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit_Identifier (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o* source, UnityEngine_Rendering_RenderTargetIdentifier_o* dest, UnityEngine_Material_o* mat, int32_t pass, UnityEngine_Vector2_o scale, UnityEngine_Vector2_o offset, int32_t sourceDepthSlice, int32_t destDepthSlice, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__GetTemporaryRT (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t antiAliasing, bool enableRandomWrite, int32_t memorylessMode, bool useDynamicScale, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__GetTemporaryRT (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t antiAliasing, bool enableRandomWrite, int32_t memorylessMode, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__GetTemporaryRT (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, int32_t antiAliasing, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__GetTemporaryRT (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__GetTemporaryRT (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, int32_t width, int32_t height, int32_t depthBuffer, int32_t filter, int32_t format, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__ReleaseTemporaryRT (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__ClearRenderTarget (UnityEngine_Rendering_CommandBuffer_o* __this, bool clearDepth, bool clearColor, UnityEngine_Color_o backgroundColor, float depth, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__ClearRenderTarget (UnityEngine_Rendering_CommandBuffer_o* __this, bool clearDepth, bool clearColor, UnityEngine_Color_o backgroundColor, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetGlobalVector (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, UnityEngine_Vector4_o value, const MethodInfo* method);
bool UnityEngine_Rendering_CommandBuffer__ValidateAgainstExecutionFlags (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t requiredFlags, int32_t invalidFlags, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetGlobalTexture_Impl (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, UnityEngine_Rendering_RenderTargetIdentifier_o* rt, int32_t element, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetRenderTarget (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o rt, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetRenderTargetSingle_Internal (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o rt, int32_t colorLoadAction, int32_t colorStoreAction, int32_t depthLoadAction, int32_t depthStoreAction, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Finalize (UnityEngine_Rendering_CommandBuffer_o* __this, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Dispose (UnityEngine_Rendering_CommandBuffer_o* __this, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Dispose (UnityEngine_Rendering_CommandBuffer_o* __this, bool disposing, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer___ctor (UnityEngine_Rendering_CommandBuffer_o* __this, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__DrawMesh (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Mesh_o* mesh, UnityEngine_Matrix4x4_o matrix, UnityEngine_Material_o* material, int32_t submeshIndex, int32_t shaderPass, UnityEngine_MaterialPropertyBlock_o* properties, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__CopyTexture (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o src, UnityEngine_Rendering_RenderTargetIdentifier_o dst, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Texture_o* source, UnityEngine_Rendering_RenderTargetIdentifier_o dest, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Texture_o* source, UnityEngine_Rendering_RenderTargetIdentifier_o dest, UnityEngine_Vector2_o scale, UnityEngine_Vector2_o offset, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Texture_o* source, UnityEngine_Rendering_RenderTargetIdentifier_o dest, UnityEngine_Material_o* mat, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o source, UnityEngine_Rendering_RenderTargetIdentifier_o dest, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o source, UnityEngine_Rendering_RenderTargetIdentifier_o dest, UnityEngine_Material_o* mat, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetGlobalVector (UnityEngine_Rendering_CommandBuffer_o* __this, System_String_o* name, UnityEngine_Vector4_o value, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetGlobalTexture (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, UnityEngine_Rendering_RenderTargetIdentifier_o value, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Internal_DrawMesh_Injected (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Mesh_o* mesh, UnityEngine_Matrix4x4_o* matrix, UnityEngine_Material_o* material, int32_t submeshIndex, int32_t shaderPass, UnityEngine_MaterialPropertyBlock_o* properties, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit_Texture_Injected (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Texture_o* source, UnityEngine_Rendering_RenderTargetIdentifier_o* dest, UnityEngine_Material_o* mat, int32_t pass, UnityEngine_Vector2_o* scale, UnityEngine_Vector2_o* offset, int32_t sourceDepthSlice, int32_t destDepthSlice, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__Blit_Identifier_Injected (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o* source, UnityEngine_Rendering_RenderTargetIdentifier_o* dest, UnityEngine_Material_o* mat, int32_t pass, UnityEngine_Vector2_o* scale, UnityEngine_Vector2_o* offset, int32_t sourceDepthSlice, int32_t destDepthSlice, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__ClearRenderTarget_Injected (UnityEngine_Rendering_CommandBuffer_o* __this, bool clearDepth, bool clearColor, UnityEngine_Color_o* backgroundColor, float depth, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetGlobalVector_Injected (UnityEngine_Rendering_CommandBuffer_o* __this, int32_t nameID, UnityEngine_Vector4_o* value, const MethodInfo* method);
void UnityEngine_Rendering_CommandBuffer__SetRenderTargetSingle_Internal_Injected (UnityEngine_Rendering_CommandBuffer_o* __this, UnityEngine_Rendering_RenderTargetIdentifier_o* rt, int32_t colorLoadAction, int32_t colorStoreAction, int32_t depthLoadAction, int32_t depthStoreAction, const MethodInfo* method);
