#pragma once

#include "il2cpp.h"

int32_t NexAssets_DataStore_Download__SearchObjectAsync (NexAssets_DataStore_Download_o* __this, NexPlugin_DataStoreSearchParam_o* param, NexPlugin_DataStore_SearchObjectCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__SearchObjectAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__SearchObjectLightAsync (NexAssets_DataStore_Download_o* __this, NexPlugin_DataStoreSearchParam_o* param, NexPlugin_DataStore_SearchObjectCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__SearchObjectLightAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetObjectAsync (NexAssets_DataStore_Download_o* __this, NexPlugin_DataStorePrepareGetParam_o* param, uint64_t bufSize, NexPlugin_DataStore_GetObjectCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetObjectAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__DeleteObjectAsync (NexAssets_DataStore_Download_o* __this, NexPlugin_DataStoreDeleteParam_o* param, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__DeleteObjectAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__DeleteObjectByDataListAsync (NexAssets_DataStore_Download_o* __this, System_Collections_Generic_List_DataStoreDeleteParam__o* paramList, bool transactional, NexPlugin_DataStore_ResultListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__DeleteObjectByDataListAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetMetaAsync (NexAssets_DataStore_Download_o* __this, NexPlugin_DataStoreGetMetaParam_o* param, NexPlugin_DataStore_GetMetaCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetMetaAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetMetaByDataListAsync (NexAssets_DataStore_Download_o* __this, System_Collections_Generic_List_ulong__o* dataIdList, NexPlugin_DataStoreGetMetaParam_o* param, NexPlugin_DataStore_GetMetaListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetMetaByDataListAsync (NexAssets_DataStore_Download_o* __this, System_Collections_Generic_List_DataStoreGetMetaParam__o* paramList, NexPlugin_DataStore_GetMetaListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetMetaByDataListAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPersistenceInfoAsync (NexAssets_DataStore_Download_o* __this, uint64_t principalId, uint16_t slotId, NexPlugin_DataStore_GetPersistenceInfoCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPersistenceInfoAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPersistenceInfoByDataListAsync (NexAssets_DataStore_Download_o* __this, uint64_t principalId, System_Collections_Generic_List_ushort__o* slotIdList, NexPlugin_DataStore_GetPersistenceInfoListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPersistenceInfoByDataListAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingAsync (NexAssets_DataStore_Download_o* __this, NexPlugin_DataStoreRatingTarget_o* param, uint64_t accessPassword, NexPlugin_DataStore_RatingInfoCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingAllSlotAsync (NexAssets_DataStore_Download_o* __this, uint64_t dataId, NexPlugin_DataStore_RatingInfoAllSlotCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingAllSlotAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingWithLogAsync (NexAssets_DataStore_Download_o* __this, NexPlugin_DataStoreRatingTarget_o* param, uint64_t accessPassword, NexPlugin_DataStore_RatingInfoWithLogCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingWithLogAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingByDataListAsync (NexAssets_DataStore_Download_o* __this, System_Collections_Generic_List_ulong__o* dataIdList, NexPlugin_DataStore_RatingInfosListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetRatingByDataListAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPasswordInfoAsync (NexAssets_DataStore_Download_o* __this, uint64_t dataId, NexPlugin_DataStore_GetPasswordInfoCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPasswordInfoAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPasswordInfoByDataListAsync (NexAssets_DataStore_Download_o* __this, System_Collections_Generic_List_ulong__o* dataIdList, NexPlugin_DataStore_GetPasswordInfoListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Download__GetPasswordInfoByDataListAsync_ (NexAssets_DataStore_Download_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
void NexAssets_DataStore_Download___ctor (NexAssets_DataStore_Download_o* __this, const MethodInfo* method_info);
