#pragma once

#include "il2cpp.h"

int32_t NexAssets_DataStore_Upload__PostObjectAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStorePreparePostParam_o* param, System_Byte_array* dataArray, NexPlugin_DataStore_PostCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostObjectAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostMetaAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStorePreparePostParam_o* param, NexPlugin_DataStore_PostCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostMetaAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostMetaByIdAsync (NexAssets_DataStore_Upload_o* __this, uint64_t dataId, NexPlugin_DataStorePreparePostParam_o* param, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostMetaByIdAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostMetaByDataListAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_ulong__o* dataIdList, NexPlugin_DataStorePreparePostParam_o* param, bool transactional, NexPlugin_DataStore_ResultListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostMetaByDataListAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_Dictionary_ulong__DataStorePreparePostParam__o* paramList, bool transactional, NexPlugin_DataStore_ResultListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PostMetaByDataListAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__CompleteSuspendedPostObjectAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_ulong__o* dataIdList, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__CompleteSuspendedPostObjectAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__UpdateObjectAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStorePrepareUpdateParam_o* param, System_Byte_array* dataArray, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__UpdateObjectAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ChangeMetaAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStoreChangeMetaParam_o* param, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ChangeMetaAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ChangeMetaByDataListAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_ulong__o* dataIdList, NexPlugin_DataStoreChangeMetaParam_o* param, bool transactional, NexPlugin_DataStore_ResultListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ChangeMetaByDataListAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_DataStoreChangeMetaParam__o* paramList, bool transactional, NexPlugin_DataStore_ResultListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ChangeMetaByDataListAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PerpetuateObjectAsync (NexAssets_DataStore_Upload_o* __this, uint16_t slotId, uint64_t dataId, bool deleteFlag, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__PerpetuateObjectAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__UnperpetuateObjectAsync (NexAssets_DataStore_Upload_o* __this, uint16_t slotId, bool deleteFlag, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__UnperpetuateObjectAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStoreRatingTarget_o* target, NexPlugin_DataStoreRateObjectParam_o* param, NexPlugin_DataStore_RatingInfoCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectByDataListAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_DataStoreRatingTarget__o* targetList, NexPlugin_DataStoreRateObjectParam_o* param, bool transactional, NexPlugin_DataStore_RatingInfoListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectByDataListAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_DataStoreRatingTarget__o* targetList, System_Collections_Generic_List_DataStoreRateObjectParam__o* paramList, bool transactional, NexPlugin_DataStore_RatingInfoListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectByDataListAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ResetRatingAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStoreRatingTarget_o* param, uint64_t accessPassword, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ResetRatingAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ResetRatingAllSlotAsync (NexAssets_DataStore_Upload_o* __this, uint64_t dataId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ResetRatingAllSlotAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ResetRatingByDataListAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_ulong__o* dataIdList, bool transactional, NexPlugin_DataStore_ResultListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__ResetRatingByDataListAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectWithPostingAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStoreRatingTarget_o* target, NexPlugin_DataStoreRateObjectParam_o* rateParam, NexPlugin_DataStorePreparePostParam_o* postParam, NexPlugin_DataStore_RatingInfoCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectWithPostingAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectsWithPostingAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_DataStoreRatingTarget__o* targetList, NexPlugin_DataStoreRateObjectParam_o* rateParam, NexPlugin_DataStorePreparePostParam_o* postParam, bool transactional, NexPlugin_DataStore_RatingInfoListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectsWithPostingAsync (NexAssets_DataStore_Upload_o* __this, System_Collections_Generic_List_DataStoreRatingTarget__o* targetList, System_Collections_Generic_List_DataStoreRateObjectParam__o* rateParamList, System_Collections_Generic_List_DataStorePreparePostParam__o* postParamList, bool transactional, NexPlugin_DataStore_RatingInfoListCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__RateObjectsWithPostingAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__TouchObjectAsync (NexAssets_DataStore_Upload_o* __this, NexPlugin_DataStoreTouchObjectParam_o* param, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_DataStore_Upload__TouchObjectAsync_ (NexAssets_DataStore_Upload_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
void NexAssets_DataStore_Upload___ctor (NexAssets_DataStore_Upload_o* __this, const MethodInfo* method_info);
