#pragma once

#include "il2cpp.h"

int32_t NexAssets_Ranking__GetRankingAsync (NexAssets_Ranking_o* __this, NexAssets_RankingGetRankingParam_o* param, uint64_t uniqueId, uint64_t principalId, bool principalIdUseCurrentLogin, NexPlugin_Ranking_GetRankingCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingAsync (NexAssets_Ranking_o* __this, int32_t rankingMode, uint32_t category, NexPlugin_RankingOrderParam_o* param, uint64_t uniqueId, uint64_t principalId, bool principalIdUseCurrentLogin, NexPlugin_Ranking_GetRankingCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingByPIDListAsync (NexAssets_Ranking_o* __this, NexAssets_RankingGetRankingParam_o* param, System_Collections_Generic_List_ulong__o* principalIdList, uint64_t uniqueId, NexPlugin_Ranking_GetRankingCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingByPIDListAsync (NexAssets_Ranking_o* __this, System_Collections_Generic_List_ulong__o* principalIdList, int32_t rankingMode, uint32_t category, NexPlugin_RankingOrderParam_o* param, uint64_t uniqueId, NexPlugin_Ranking_GetRankingCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingByPIDListAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingByUIDListAsync (NexAssets_Ranking_o* __this, NexAssets_RankingGetRankingParam_o* param, System_Collections_Generic_List_ulong__o* nexUniqueIdList, uint64_t uniqueId, NexPlugin_Ranking_GetRankingCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingByUIDListAsync (NexAssets_Ranking_o* __this, System_Collections_Generic_List_ulong__o* nexUniqueIdList, int32_t rankingMode, uint32_t category, NexPlugin_RankingOrderParam_o* param, uint64_t uniqueId, NexPlugin_Ranking_GetRankingCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetRankingByUIDListAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetApproxOrderAsync (NexAssets_Ranking_o* __this, NexAssets_RankingGetRankingParam_o* param, uint32_t score, uint64_t uniqueId, uint64_t principalId, bool principalIdUseCurrentLogin, NexPlugin_Ranking_GetApproxOrderCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetApproxOrderAsync (NexAssets_Ranking_o* __this, uint32_t category, NexPlugin_RankingOrderParam_o* param, uint32_t score, uint64_t uniqueId, uint64_t principalId, bool principalIdUseCurrentLogin, NexPlugin_Ranking_GetApproxOrderCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetApproxOrderAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__UploadScoreAsync (NexAssets_Ranking_o* __this, NexAssets_RankingScoreData_o* scoreData, uint32_t score, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__UploadScoreAsync (NexAssets_Ranking_o* __this, NexPlugin_RankingScoreData_o* param, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__UploadScoreAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__DeleteScoreAsync (NexAssets_Ranking_o* __this, uint32_t category, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__DeleteScoreAsync (NexAssets_Ranking_o* __this, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__DeleteScoreAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__UploadCommonDataAsync (NexAssets_Ranking_o* __this, System_Collections_Generic_List_byte__o* param, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__UploadCommonDataAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetCommonDataAsync (NexAssets_Ranking_o* __this, uint64_t uniqueId, NexPlugin_Ranking_GetCommonDataCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetCommonDataAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__DeleteCommonDataAsync (NexAssets_Ranking_o* __this, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__DeleteCommonDataAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetStatsAsync (NexAssets_Ranking_o* __this, NexAssets_RankingGetRankingParam_o* param, NexPlugin_Ranking_GetStatsCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetStatsAsync (NexAssets_Ranking_o* __this, uint32_t category, NexPlugin_RankingOrderParam_o* param, int32_t flags, NexPlugin_Ranking_GetStatsCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetStatsAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__ChangeAttributesAsync (NexAssets_Ranking_o* __this, uint32_t category, NexPlugin_RankingChangeAttributesParam_o* param, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__ChangeAttributesAsync (NexAssets_Ranking_o* __this, NexPlugin_RankingChangeAttributesParam_o* param, uint64_t uniqueId, NexPlugin_AsyncResultCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__ChangeAttributesAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetCachedTopXRankingAsync (NexAssets_Ranking_o* __this, uint32_t category, NexPlugin_RankingOrderParam_o* param, NexPlugin_Ranking_GetCachedTopXRankingCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetCachedTopXRankingAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetCachedTopXRankingsAsync (NexAssets_Ranking_o* __this, System_Collections_Generic_List_uint__o* categorieList, NexPlugin_RankingOrderParam_o* param, NexPlugin_Ranking_GetCachedTopXRankingsCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetCachedTopXRankingsAsync (NexAssets_Ranking_o* __this, System_Collections_Generic_List_uint__o* categorieList, System_Collections_Generic_List_RankingOrderParam__o* paramList, NexPlugin_Ranking_GetCachedTopXRankingsCB_o* callback, intptr_t pNgsFacade, int32_t timeOut, const MethodInfo* method_info);
int32_t NexAssets_Ranking__GetCachedTopXRankingsAsync_ (NexAssets_Ranking_o* __this, NexPlugin_AsyncResult_o* asyncResult, NexAssets_Common_CORE_ARG_o* param, const MethodInfo* method_info);
bool NexAssets_Ranking__ApiCallsFrequencyCheck (NexAssets_Ranking_o* __this, int32_t type, const MethodInfo* method_info);
void NexAssets_Ranking___ctor (NexAssets_Ranking_o* __this, const MethodInfo* method_info);
void NexAssets_Ranking___cctor (const MethodInfo* method_info);
