#pragma once

#include "il2cpp.h"

bool NexPlugin_Ranking__UploadCommonDataAsync (uint32_t* asyncId, intptr_t pNgsFacade, System_Collections_Generic_List_byte__o* commonData, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_AsyncResultCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__DeleteCommonDataAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_AsyncResultCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetCommonDataAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_Ranking_GetCommonDataCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__UploadScoreAsync (uint32_t* asyncId, intptr_t pNgsFacade, NexPlugin_RankingScoreData_o* scoreData, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_AsyncResultCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__DeleteScoreAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint32_t category, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_AsyncResultCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__DeleteScoreAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_AsyncResultCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetRankingAsync (uint32_t* asyncId, intptr_t pNgsFacade, int32_t rankingMode, uint32_t category, NexPlugin_RankingOrderParam_o* orderParam, uint64_t nexUniqueId, uint64_t principalId, int32_t timeOut, NexPlugin_Ranking_GetRankingCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetRankingByPIDListAsync (uint32_t* asyncId, intptr_t pNgsFacade, System_Collections_Generic_List_ulong__o* principalIdList, int32_t rankingMode, uint32_t category, NexPlugin_RankingOrderParam_o* orderParam, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_Ranking_GetRankingCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetRankingByUIDListAsync (uint32_t* asyncId, intptr_t pNgsFacade, System_Collections_Generic_List_ulong__o* nexUniqueIdList, int32_t rankingMode, uint32_t category, NexPlugin_RankingOrderParam_o* orderParam, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_Ranking_GetRankingCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetApproxOrderAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint32_t category, NexPlugin_RankingOrderParam_o* orderParam, uint32_t score, uint64_t nexUniqueId, uint64_t principalId, int32_t timeOut, NexPlugin_Ranking_GetApproxOrderCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetStatsAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint32_t category, NexPlugin_RankingOrderParam_o* orderParam, int32_t flags, int32_t timeOut, NexPlugin_Ranking_GetStatsCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__ChangeAttributesAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint32_t category, NexPlugin_RankingChangeAttributesParam_o* changeParam, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_AsyncResultCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__ChangeAttributesAsync (uint32_t* asyncId, intptr_t pNgsFacade, NexPlugin_RankingChangeAttributesParam_o* changeParam, uint64_t nexUniqueId, int32_t timeOut, NexPlugin_AsyncResultCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetCachedTopXRankingAsync (uint32_t* asyncId, intptr_t pNgsFacade, uint32_t category, NexPlugin_RankingOrderParam_o* orderParam, int32_t timeOut, NexPlugin_Ranking_GetCachedTopXRankingCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetCachedTopXRankingsAsync (uint32_t* asyncId, intptr_t pNgsFacade, System_Collections_Generic_List_uint__o* categories, NexPlugin_RankingOrderParam_o* orderParam, int32_t timeOut, NexPlugin_Ranking_GetCachedTopXRankingsCB_o* callback, const MethodInfo* method);
bool NexPlugin_Ranking__GetCachedTopXRankingsAsync (uint32_t* asyncId, intptr_t pNgsFacade, System_Collections_Generic_List_uint__o* categories, System_Collections_Generic_List_RankingOrderParam__o* orderParams, int32_t timeOut, NexPlugin_Ranking_GetCachedTopXRankingsCB_o* callback, const MethodInfo* method);
